export { SignIn } from "./SignIn";
export { Welcome } from "./Welcome";
export { VerifyOtp } from "./VerifyOtp";
export { CaptureImage } from "./CaptureImage";
export { ForgetPassword } from "./ForgetPassword";
export { CreateAccount } from "./CreateAccount";
export { VerifyDetails } from "./VerifyDetails";
export { PictureChoice } from "./PictureChoice";
export { SignupDateofBirth } from "./SignupDateofBirth";
